project_id = "vbwhtwocpobplearoooq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.check-scheduled-events]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-family-invitation]
verify_jwt = false

[functions.test-simple]
verify_jwt = false

[functions.test-notifications]
verify_jwt = false

[functions.create-test-event]
verify_jwt = false

[functions.reset-notifications]
verify_jwt = false

[functions.test-push-simple]
verify_jwt = false

[functions.debug-notifications]
verify_jwt = false

[functions.force-notification]
verify_jwt = false

[functions.create-future-event]
verify_jwt = false

[functions.test-notification-now]
verify_jwt = false

[functions.debug-push-test]
verify_jwt = false

[functions.test-push-direct]
verify_jwt = false

[functions.comprehensive-push-debug]
verify_jwt = false

[functions.test-firebase-config]
verify_jwt = false

[functions.debug-token-save]
verify_jwt = false

[functions.collect-debug-logs]
verify_jwt = false

[functions.trigger-notifications]
verify_jwt = false