default_platform(:ios)

platform :ios do
  desc "Build & upload to TestFlight"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      is_key_content_base64: false
    )

    # Χρησιμοποίησε τον login keychain του runner
    match(
      type: "appstore",
      readonly: true,
      keychain_name: "login.keychain-db"
    )

    # ⬇️ ΔΗΛΩΣΕ ΡΗΤΑ project + target + team
    update_project_team(
      path: "App.xcodeproj",
      teamid: ENV["APPLE_TEAM_ID"],
      targets: ["App"]
    )

    automatic_code_signing(
      path: "App.xcodeproj",
      use_automatic_signing: true,
      team_id: ENV["APPLE_TEAM_ID"],
      targets: ["App"]
    )

    # Build (το workspace είναι μέσα στο ios/App)
    gym(
      scheme: "App",
      workspace: "App.xcworkspace",   # ή απλά αφαίρεσέ το και θα το βρει μόνο του
      configuration: "Release",
      export_method: "app-store",
      export_options: { signingStyle: "automatic" }
    )

    upload_to_testflight(
      app_identifier: ENV['APPLE_APP_ID'],
      skip_waiting_for_build_processing: true
    )
  end
end
