// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbwhtwocpobplearoooq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid2h0d29jcG9icGxlYXJvb29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODQ0OTgsImV4cCI6MjA2ODA2MDQ5OH0.Ui3q4plAY6QmO6M64s8_K4667FXHKm_ukiawPhC1IR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});