require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
platform :ios, '14.0'
use_frameworks!

# Force Firebase to use compatible versions
pod 'Firebase/Core', '~> 10.24.0'
pod 'Firebase/Messaging', '~> 10.24.0'
pod 'FirebaseCore', '~> 10.24.0'
pod 'FirebaseMessaging', '~> 10.24.0'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		  # ΑΛΛΑΞΕ ΤΟ ΑΥΤΟ ΣΕ 14.0!
		  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0' 
		  
		  # Αυτό μπορείς να το κρατήσεις, είναι χρήσιμο
		  config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
		end
	  end
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0' # ίδιο με το παραπάνω
        # Προαιρετικά για Xcode 16 warnings:
        c.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      end
    end
end
