# ios/App/Podfile

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
platform :ios, '14.0'
use_frameworks!

# Force Firebase to use compatible versions
pod 'Firebase/Core', '~> 10.24.0'
pod 'Firebase/Messaging', '~> 10.24.0'
pod 'FirebaseCore', '~> 10.24.0'
pod 'FirebaseMessaging', '~> 10.24.0'

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

# --- ΤΕΛΙΚΟ ΚΑΙ ΣΥΝΟΛΙΚΟ SCRIPT ΔΙΟΡΘΩΣΗΣ ---
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		  # 1. Ορίζουμε το σωστό deployment target
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0' 
        
        # 2. Απενεργοποιούμε το code signing για τα Pods
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        
        # 3. ΑΠΕΝΕΡΓΟΠΟΙΟΥΜΕ ΕΝΤΕΛΩΣ ΤΟ SWIFT OPTIMIZATION (Η ΛΥΣΗ)
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
		end
	end
end
