name: Build Android AAB

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Signed AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install --global @capacitor/cli

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Set up Java 21
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant Gradlew permission
        run: chmod +x android/gradlew

      - name: Decode keystore from GitHub secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks


      - name: Clean Android build
        working-directory: android
        run: |
          ./gradlew clean
          rm -rf build/
          rm -rf app/build/

      - name: Verify file exists
        run: |
          ls -l "${{ github.workspace }}/android/app/"

      - name: Verify keystore exists
        run: ls -l android/app/my-release-key.jks


      - name: Build signed AAB
        working-directory: android
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
