name: Match Repair (certs)

on:
  workflow_dispatch:
    inputs:
      type:
        description: Match type (appstore / development / adhoc)
        required: true
        default: appstore

jobs:
  repair:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: '2.5.14'
          bundler-cache: true
          working-directory: ios/App

      # SSH key για να κάνει push στο certs repo
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Repair certs/profiles in match repo
        working-directory: ios/App
        env:
          MATCH_GIT_URL: git@github.com:araksia/formypet-ios-certificates.git
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        run: |
          bundle install
          bundle exec fastlane match repair \
            --type "${{ github.event.inputs.type }}" \
            --git_url "$MATCH_GIT_URL" \
            --git_branch master \
            --team_id "$APPLE_TEAM_ID"
