name: Renew App Store Profile
on:
  workflow_dispatch: {}

jobs:
  renew:
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    env:
      APP_BUNDLE_ID: gr.formypet.app
      TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_GIT_BRANCH: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane
        working-directory: ios/App
        run: |
          set -e
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Start ssh-agent (match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Known hosts & git identity
        run: |
          set -e
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"
          git ls-remote "$MATCH_GIT_URL" -h

      # 1) Normalize ASC key secret (raw PEM or base64) -> AuthKey.p8
      - name: Normalize App Store Connect API key
        env:
          ASC_INPUT: ${{ secrets.APP_STORE_CONNECT_API_KEY_PEM }}
        run: |
          set -e
          printf "%s" "$ASC_INPUT" > key_input.txt
          if grep -q "BEGIN PRIVATE KEY" key_input.txt; then
            mv key_input.txt AuthKey.p8
          else
            (base64 --decode key_input.txt > AuthKey.p8 2>/dev/null) || \
            (base64 -d key_input.txt > AuthKey.p8 2>/dev/null) || \
            (python3 - <<'PY'
            import base64,sys
            open("AuthKey.p8","wb").write(base64.b64decode(open("key_input.txt","rb").read()))
            PY
            )
          fi
          /usr/bin/openssl pkey -in AuthKey.p8 -noout -text | head -n 8
          # Export decoded PEM as multi-line env for next action
          {
            echo "APP_STORE_CONNECT_API_KEY_PEM_DECODED<<__EOF__"
            cat AuthKey.p8
            echo "__EOF__"
          } >> "$GITHUB_ENV"

      # 2) Build api-key.json using decoded PEM
      - name: Create App Store Connect API JSON
        uses: akiojin/setup-store-connect-api-json-github-action@v1.0.11
        with:
          key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          issuer-id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          key: ${{ env.APP_STORE_CONNECT_API_KEY_PEM_DECODED }}

      # 3) Ensure Matchfile has correct team_id & app_identifier
      - name: Fix Matchfile (team_id & app_identifier)
        working-directory: ios/App/fastlane
        run: |
          set -e
          if [ ! -f Matchfile ]; then touch Matchfile; fi
          if grep -qE '^\s*team_id' Matchfile; then
            sed -i.bak -E "s/^\s*team_id.*/team_id(\"$TEAM_ID\")/" Matchfile
          else
            printf '\nteam_id("%s")\n' "$TEAM_ID" >> Matchfile
          fi
          if grep -qE '^\s*app_identifier' Matchfile; then
            sed -i.bak -E "s#^\s*app_identifier.*#app_identifier([\"$APP_BUNDLE_ID\"])#" Matchfile
          else
            printf 'app_identifier(["%s"])\n' "$APP_BUNDLE_ID" >> Matchfile
          fi
          tail -n +1 Matchfile

      - name: Create temp keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          set -e
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

      - name: Create/Update App Store provisioning profile
        working-directory: ios/App
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          set -e
          bundle exec fastlane run match \
            readonly:false \
            type:appstore \
            api_key_path:$APP_STORE_CONNECT_API_KEY_PATH \
            app_identifier:$APP_BUNDLE_ID \
            team_id:$TEAM_ID \
            git_url:$MATCH_GIT_URL \
            git_branch:$MATCH_GIT_BRANCH \
            clone_branch_directly:true \
            shallow_clone:false \
            keychain_name:build.keychain \
            keychain_password:$KEYCHAIN_PASSWORD
