name: Bootstrap Match Profiles
on:
  workflow_dispatch: {}

jobs:
  make-profiles:
    runs-on: macos-14
    env:
      APP_BUNDLE_ID: "gr.formypet.app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane (and deps)
        working-directory: ios/App
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Start ssh-agent (for match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git identity
        run: |
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"

      - name: Check access to match repo
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          if [ -z "$MATCH_GIT_URL" ]; then echo "MATCH_GIT_URL is empty"; exit 1; fi
          git ls-remote "$MATCH_GIT_URL" -h

      - name: Create ASC API key JSON (action)
        uses: akiojin/setup-store-connect-api-json-github-action@v1.0.11
        with:
          key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          issuer-id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          key: ${{ secrets.APP_STORE_CONNECT_API_KEY_PEM }}

      - name: Ensure Matchfile has app_identifier
        working-directory: ios/App/fastlane
        env:
          APP_BUNDLE_ID: ${{ env.APP_BUNDLE_ID }}
        run: |
          if grep -qE '^[[:space:]]*app_identifier' Matchfile; then
            sed -i.bak -E "s#^[[:space:]]*app_identifier.*#app_identifier([\"$APP_BUNDLE_ID\"])#g" Matchfile
          else
            printf '\napp_identifier(["%s"])\n' "$APP_BUNDLE_ID" >> Matchfile
          fi
          tail -n +1 Matchfile

      - name: Create/Update App Store profile
        working-directory: ios/App
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BRANCH: main
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          bundle exec fastlane run match readonly:false type:appstore api_key_path:$APP_STORE_CONNECT_API_KEY_PATH app_identifier:$APP_BUNDLE_ID team_id:$APPLE_TEAM_ID

      - name: Create/Update Development profile
        working-directory: ios/App
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BRANCH: main
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          bundle exec fastlane run match readonly:false type:development api_key_path:$APP_STORE_CONNECT_API_KEY_PATH app_identifier:$APP_BUNDLE_ID team_id:$APPLE_TEAM_ID
