name: Bootstrap Match Profiles
on:
  workflow_dispatch: {}

jobs:
  make-profiles:
    runs-on: macos-14
    env:
      APP_BUNDLE_ID: "gr.formypet.app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane (and deps)
        working-directory: ios/App
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Start ssh-agent (for match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git identity
        run: |
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"

      - name: Check access to match repo
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          if [ -z "$MATCH_GIT_URL" ]; then echo "MATCH_GIT_URL is empty"; exit 1; fi
          git ls-remote "$MATCH_GIT_URL" -h

      - name: Build asc_api_key.json from secrets
        working-directory: ios/App
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          ASC
