name: Bootstrap App Store Profile
on:
  workflow_dispatch: {}

jobs:
  bootstrap:
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    env:
      APP_BUNDLE_ID: gr.formypet.app
      TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_GIT_BRANCH: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane
        working-directory: ios/App
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Start ssh-agent (match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Known hosts & git identity
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"
          git ls-remote "$MATCH_GIT_URL" -h

      # Προαιρετικός έλεγχος ότι το .p8 είναι ΕC (prime256v1)
      - name: Quick OpenSSL check (ASC API key)
        env:
          ASC_PEM: ${{ secrets.APP_STORE_CONNECT_API_KEY_PEM }}
        run: |
          printf "%s" "$ASC_PEM" > AuthKey.p8
          /usr/bin/openssl pkey -in AuthKey.p8 -noout -text | head -n 8 || { echo "Invalid .p8 key"; exit 1; }

      # Φτιάχνει το api-key.json και ορίζει APP_STORE_CONNECT_API_KEY_PATH
      - name: Create App Store Connect API JSON
        uses: akiojin/setup-store-connect-api-json-github-action@v1.0.11
        with:
          key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          issuer-id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          key: ${{ secrets.APP_STORE_CONNECT_API_KEY_PEM }}

      - name: Create temp keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

      - name: Create/Update App Store provisioning profile
        working-directory: ios/App
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          bundle exec fastlane run match \
            readonly:false \
            type:appstore \
            api_key_path:$APP_STORE_CONNECT_API_KEY_PATH \
            app_identifier:$APP_BUNDLE_ID \
            team_id:$TEAM_ID \
            git_url:$MATCH_GIT_URL \
            git_branch:$MATCH_GIT_BRANCH \
            clone_branch_directly:true \
            shallow_clone:false \
            keychain_name:build.keychain \
            keychain_password:$KEYCHAIN_PASSWORD
