name: Bootstrap Match Profiles
on:
  workflow_dispatch: {}

jobs:
  make-profiles:
    runs-on: macos-14
    env:
      APP_BUNDLE_ID: "gr.formypet.app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane (and deps)
        working-directory: ios/App
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      # SSH για πρόσβαση WRITE στο match repo (Deploy key στο secret)
      - name: Start ssh-agent (for match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git identity
        run: |
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"

      - name: Check access to match repo
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          if [ -z "$MATCH_GIT_URL" ]; then echo "MATCH_GIT_URL is empty"; exit 1; fi
          git ls-remote "$MATCH_GIT_URL" -h

      # Φτιάχνουμε asc_api_key.json από τα 3 secrets (ID, ISSUER, .p8 base64)
      - name: Build ASC API key JSON from 3 secrets
        working-directory: ios/App
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          ASC_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          set -e
          if [ -z "$ASC_KEY_ID" ] || [ -z "$ASC_ISSUER_ID" ] || [ -z "$ASC_KEY_B64" ]; then
            echo "Missing one of APP_STORE_CONNECT_API_KEY_ID / _ISSUER_ID / _KEY"; exit 1
          fi
          echo "$ASC_KEY_B64" | base64 --decode > AuthKey.p8
          KEY_ESCAPED=$(awk '{gsub(/\r/,""); printf "%s\\n", $0}' AuthKey.p8)
          {
            echo '{'
            echo "  \"key_id\": \"${ASC_KEY_ID}\","
            echo "  \"issuer_id\": \"${ASC_ISSUER_ID}\","
            echo "  \"key\": \"${KEY_ESCAPED}\","
            echo '  "in_house": false'
            echo '}'
          } > asc_api_key.json
          test -s asc_api_key.json || { echo "asc_api_key.json empty"; cat asc_api_key.json; exit 1; }

      # Βεβαιώσου ότι το Matchfile έχει το app_identifier σωστά
      - name: Ensure Matchfile has app_identifier
        working-directory: ios/App/fastlane
        env:
          APP_BUNDLE_ID: ${{ env.APP_BUNDLE_ID }}
        run: |
          if grep -qE '^[[:space:]]*app_identifier' Matchfile; then
            sed -i.bak -E "s#^[[:space:]]*app_identifier.*#app_identifier([\"$APP_BUNDLE_ID\"])#g" Matchfile
          else
            printf '\napp_identifier(["%s"])\n' "$APP_BUNDLE_ID" >> Matchfile
          fi
          tail -n +1 Matchfile

      # Δημιουργία/Ανανέωση App Store (production aps)
      - name: Create/Update App Store profile
        working-directory: ios/App
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BRANCH: main
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPL
