name: Renew App Store Profile
on:
  workflow_dispatch: {}

jobs:
  renew:
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    env:
      APP_BUNDLE_ID: gr.formypet.app
      TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_GIT_BRANCH: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane
        working-directory: ios/App
        run: |
          set -e
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Start ssh-agent (match repo)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Known hosts & git identity
        run: |
          set -e
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions"
          git ls-remote "$MATCH_GIT_URL" -h

      # 1) Normalize ASC key secret (raw PEM or base64) -> AuthKey.p8
      - name: Normalize App Store Connect API key
        env:
          ASC_INPUT: ${{ secrets.APP_STORE_CONNECT_API_KEY_PEM }}
        run: |
          set -e
          printf "%s" "$ASC_INPUT" > key_input.txt
          if grep -q "BEGIN PRIVATE KEY" key_input.txt; then
            mv key_input.txt AuthKey.p8
          else
            (base64 --decode key_input.txt > AuthKey.p8 2>/dev/null) || \
            (base64 -d key_input.txt > AuthKey.p8 2>/dev/null) || \
            (python3 - <<'PY'
            import base64,sys
            open("AuthKey.p8","wb").write(base64.b64decode(open("key_input.txt","rb").read()))
            PY
            )
          fi
          /usr/bin/openssl pkey -in AuthKey.p8 -noout -text | head -n 8
